#GET http://localhost:4000/user/check/nickname/허허허

#GET http://localhost:4000/api/travel
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1NTE0MDExM30.SAnoYMJVL9oW-bXKyJnthyehBTvaJhIAEXIeEui3jeA
#DELETE http://localhost:4000/api/travels/5
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1NTE0MDExM30.SAnoYMJVL9oW-bXKyJnthyehBTvaJhIAEXIeEui3jeA
#PATCH http://localhost:4000/api/travels/6
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1NTE0MDExM30.SAnoYMJVL9oW-bXKyJnthyehBTvaJhIAEXIeEui3jeA
#Content-Type: application/json
#
#{
#  "title": "머냐고..",
#  "content": "먼데"
#}
#POST http://localhost:4000/api/travels
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1NTE0MDExM30.SAnoYMJVL9oW-bXKyJnthyehBTvaJhIAEXIeEui3jeA
#Content-Type: application/json
#
#{
#"title": "title",
#"content": "content"
#}


#http://3.37.87.166/user/login
#POST http://localhost:4000/user/login
#Content-Type: application/json
#
#
#{
#  "email":"test123456@test.com",
#  "password":"qwer12345"
#}
POST http://3.37.87.166/user/login
Content-Type: application/json

{
  "email":"a@a.com",
  "password": "a"
}
