#GET http://localhost:4000/user/check/nickname/허허허

###
// delete
DELETE http://localhost:4000/api/travels/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1NTE0MDExM30.SAnoYMJVL9oW-bXKyJnthyehBTvaJhIAEXIeEui3jeA

###
// 수정
PATCH http://localhost:4000/api/travels/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1NTE0MDExM30.SAnoYMJVL9oW-bXKyJnthyehBTvaJhIAEXIeEui3jeA
Content-Type: application/json

{
  "title": "머냐고..",
  "content": "먼데"
}

###
// 등록
POST http://localhost:4000/api/travels
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1NTE0MDExM30.SAnoYMJVL9oW-bXKyJnthyehBTvaJhIAEXIeEui3jeA
Content-Type: application/json

{
"title": "title",
"content": "content"
}


###
// 아마존 로그인
POST http://localhost:4000/user/login
Content-Type: application/json

{
  "email":"test123456@test.com",
  "password":"qwer12345"
}

###
// 회원가입
POST http://3.37.87.166/user/signup
Content-Type: application/json

{
  "email":"z@z.com",
  "nickname": "명지분식",
  "password": "a"
}

###
#iamport 토큰 겟
POST http://localhost:4000/admin/get-iamport-token

###
//restaurant
POST http://localhost:4000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1NTE0MDExM30.SAnoYMJVL9oW-bXKyJnthyehBTvaJhIAEXIeEui3jeA
Content-Type: application/json

[
  {
    "name": "족발나라",
    "categoryId": 1,
    "location": "영등포점",
    "phone": "07012345678",
    "img": "url",
    "openingHours": "오전11시",
    "minPrice": 20000,
    "logoImg": "logoImg"
  },
  {
    "menuName": "족발(大)",
    "price": 30000,
    "explain": "일본이 놀라 자빠지고 중국이 탐내는 족발",
    "menuImg": "menuImg"
  },
  {
    "menuName": "보쌈(大)",
    "price": 30000,
    "explain": "보쌈 존맛",
    "menuImg": "menuImg"
  }
]


###
//detailPage
GET http://localhost:4000/api/post/11
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1NTE0MDExM30.SAnoYMJVL9oW-bXKyJnthyehBTvaJhIAEXIeEui3jeA